name: detect_clap_sound_flutter
description: "A library for detecting types of sounds during audio recording (e.g., clapping, whistling, etc.)"
version: 1.1.2
homepage: https://github.com/AnhPhon/detect_clap_sound_flutter

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: techmind.studio.detect_clap_sound_flutter
        pluginClass: DetectClapSoundFlutterPlugin
